#!/bin/sh
rm /tmp/cryptostuff/t1/*
rm /tmp/cryptostuff/t3/*
rm /tmp/cryptostuff/sendfiles/*
rm /tmp/cryptostuff/receivefiles/*
rm /tmp/cryptostuff/rawkey/*
rm /tmp/cryptostuff/transferlog2
rm /tmp/cryptostuff/choplog2
rm /tmp/cryptostuff/cmdins
rm /tmp/cryptostuff/msgin2
rm /tmp/cryptostuff/chopdebug
